<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- xunit v3 test projeleri çalıştırılabilirdir. -->
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/GitExt.Core/GitExt.Core.csproj" />
  </ItemGroup>

</Project>
