#!/usr/bin/env python3
"""Generates the embedded fallback translation class from `en.json` (P11-T10).

    tools/i18n/generate-fallback.py           # generate
    tools/i18n/generate-fallback.py --check   # is it up to date? (for CI)

⚠️ WHY IT EXISTS: `Translator` falls back to English on a missing key, but that English came
from `en.json` too. If the file is deleted or corrupted the fallback becomes an **empty
dictionary** and the UI fills up with key names ("settings.language"). Measured — without
`en.json`, every key missing from TR shows as the raw key.

So the English texts are EMBEDDED in the code: they depend on no file, cannot be deleted and
cannot be corrupted. They are not written by hand — they are generated from `en.json`, so the
two sources cannot diverge. `--check` verifies that in CI.
"""

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = ROOT / "src" / "GitExt.UI" / "Locales" / "en.json"
TARGET = ROOT / "src" / "GitExt.UI" / "Localization" / "BuiltInEnglish.cs"

HEADER = '''// <auto-generated>
//     This file was GENERATED from src/GitExt.UI/Locales/en.json by
//     tools/i18n/generate-fallback.py. Do not edit by hand — to change a text, edit en.json
//     and run the script again.
// </auto-generated>

using System.Collections.Frozen;

namespace GitExt.UI.Localization;

/// <summary>
/// The copy of the English texts embedded in the code (P11-T10).
/// </summary>
/// <remarks>
/// <para>
/// 🔴 <b>Why embedded:</b> <see cref="Translator"/> falls back to English on a missing key, but that
/// English came from <c>en.json</c> too. If the file were deleted or corrupted the fallback became an
/// <b>empty dictionary</b> and the UI filled up with key names (such as <c>settings.language</c>).
/// Measured and confirmed.
/// </para>
/// <para>
/// The copy here depends on no file: it cannot be deleted, cannot be corrupted, and is unaffected by
/// trimming. It costs ~32 KB.
/// </para>
/// <para>
/// <b>It is not written by hand.</b> It is generated from <c>en.json</c> and CI
/// (<c>generate-fallback.py --check</c>) verifies the two have not diverged — with two separate
/// English sources they would sooner or later differ.
/// </para>
/// </remarks>
internal static class BuiltInEnglish
{
    /// <summary>Key → English text.</summary>
    public static FrozenDictionary<string, string> Entries { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
'''

FOOTER = '''        }.ToFrozenDictionary(StringComparer.Ordinal);
}
'''


def escape(text: str) -> str:
    """Escaping for a C# string literal."""
    return (text
            .replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t"))


def render() -> str:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    data.pop("_meta", None)

    lines = [HEADER]

    for key in sorted(data):
        lines.append(f'            ["{escape(key)}"] = "{escape(data[key])}",\n')

    lines.append(FOOTER)
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = render()

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""

        if current != generated:
            print(
                "ERROR: BuiltInEnglish.cs DOES NOT MATCH en.json.\n"
                "  Run tools/i18n/generate-fallback.py and commit the result.",
                file=sys.stderr)
            return 1

        print("OK: the embedded English matches en.json.")
        return 0

    TARGET.write_text(generated, encoding="utf-8")
    count = generated.count("] = \"")
    print(f"{TARGET.relative_to(ROOT)}: {count} keys")
    return 0


if __name__ == "__main__":
    sys.exit(main())
