#!/usr/bin/env python3
"""`en.json`'dan gömülü yedek çeviri sınıfı üretir (P11-T10).

    tools/i18n/generate-fallback.py           # üret
    tools/i18n/generate-fallback.py --check   # güncel mi? (CI için)

⚠️ NEDEN VAR: `Translator` eksik anahtarda İngilizceye düşüyor, ama o İngilizce de
`en.json`'dan geliyordu. Dosya silinir/bozulursa yedek **boş sözlük** olur ve arayüz
anahtar adlarıyla dolar ("settings.language"). Ölçüldü — `en.json` yokken TR'de olmayan
her anahtar ham anahtar olarak görünüyor.

Bu yüzden İngilizce metinler koda GÖMÜLÜYOR: hiçbir dosyaya bağlı değil, silinemez,
bozulamaz. Elle yazılmıyor — `en.json`'dan üretiliyor, böylece iki kaynak ayrışamaz.
`--check` bunu CI'da doğruluyor.
"""

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = ROOT / "src" / "GitExt.UI" / "Locales" / "en.json"
TARGET = ROOT / "src" / "GitExt.UI" / "Localization" / "BuiltInEnglish.cs"

HEADER = '''// <auto-generated>
//     Bu dosya tools/i18n/generate-fallback.py tarafından src/GitExt.UI/Locales/en.json'dan
//     ÜRETİLDİ. Elle düzenlemeyin — metni değiştirmek için en.json'u düzenleyip betiği
//     yeniden çalıştırın.
// </auto-generated>

using System.Collections.Frozen;

namespace GitExt.UI.Localization;

/// <summary>
/// İngilizce metinlerin koda gömülü kopyası (P11-T10).
/// </summary>
/// <remarks>
/// <para>
/// 🔴 <b>Neden gömülü:</b> <see cref="Translator"/> eksik bir anahtarda İngilizceye düşüyor,
/// ama o İngilizce de <c>en.json</c>'dan geliyordu. Dosya silinirse ya da bozulursa yedek
/// <b>boş sözlük</b> oluyor ve arayüz anahtar adlarıyla doluyordu
/// (<c>settings.language</c> gibi). Ölçüldü ve doğrulandı.
/// </para>
/// <para>
/// Buradaki kopya hiçbir dosyaya bağlı değil: silinemez, bozulamaz, trimming'den
/// etkilenmez. Maliyeti ~32 KB.
/// </para>
/// <para>
/// <b>Elle yazılmıyor.</b> <c>en.json</c>'dan üretiliyor ve CI
/// (<c>generate-fallback.py --check</c>) ikisinin ayrışmadığını doğruluyor — iki ayrı
/// İngilizce kaynağı olsaydı er ya da geç farklılaşırlardı.
/// </para>
/// </remarks>
internal static class BuiltInEnglish
{
    /// <summary>Anahtar → İngilizce metin.</summary>
    public static FrozenDictionary<string, string> Entries { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
'''

FOOTER = '''        }.ToFrozenDictionary(StringComparer.Ordinal);
}
'''


def escape(text: str) -> str:
    """C# dize sabiti için kaçış."""
    return (text
            .replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t"))


def render() -> str:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    data.pop("_meta", None)

    lines = [HEADER]

    for key in sorted(data):
        lines.append(f'            ["{escape(key)}"] = "{escape(data[key])}",\n')

    lines.append(FOOTER)
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = render()

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""

        if current != generated:
            print(
                "HATA: BuiltInEnglish.cs, en.json ile UYUŞMUYOR.\n"
                "  tools/i18n/generate-fallback.py çalıştırıp sonucu commit'leyin.",
                file=sys.stderr)
            return 1

        print("OK: gömülü İngilizce, en.json ile aynı.")
        return 0

    TARGET.write_text(generated, encoding="utf-8")
    count = generated.count("] = \"")
    print(f"{TARGET.relative_to(ROOT)}: {count} anahtar")
    return 0


if __name__ == "__main__":
    sys.exit(main())
